import type { Product, Combo } from './types';

export const mockProducts: Product[] = [
  {
    id: 'PRD001',
    name: 'Bộ chăn ga gối Baby Dream',
    sku: 'BD-SET-001',
    type: 'single',
    category: 'Bộ chăn ga',
    price: 599000,
    salePrice: 499000,
    stock: 45,
    status: 'active',
    images: ['/images/products/baby-dream-1.jpg'],
    description: 'Bộ chăn ga gối cao cấp cho bé từ 0-3 tuổi, chất liệu cotton 100%',
    featured: true,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-02-05T14:30:00Z',
    sales: 128,
  },
  {
    id: 'PRD002',
    name: 'Gối ôm thú bông Unicorn',
    sku: 'UC-PIL-002',
    type: 'single',
    category: 'Gối',
    price: 299000,
    stock: 0,
    status: 'out_of_stock',
    images: ['/images/products/unicorn-pillow.jpg'],
    description: 'Gối ôm hình unicorn siêu dễ thương, an toàn cho trẻ em',
    featured: true,
    createdAt: '2026-01-20T09:00:00Z',
    updatedAt: '2026-02-06T08:00:00Z',
    sales: 89,
  },
  {
    id: 'PRD003',
    name: 'Chăn mền 4 mùa Comfort',
    sku: 'CF-BLK-003',
    type: 'single',
    category: 'Chăn',
    price: 450000,
    salePrice: 380000,
    stock: 67,
    status: 'active',
    images: ['/images/products/comfort-blanket.jpg'],
    description: 'Chăn mền 4 mùa ấm áp, thấm hút tốt',
    featured: false,
    createdAt: '2026-01-10T11:00:00Z',
    updatedAt: '2026-02-01T16:00:00Z',
    sales: 156,
  },
  {
    id: 'PRD004',
    name: 'Ga giường họa tiết vũ trụ',
    sku: 'SP-SHT-004',
    type: 'single',
    category: 'Ga giường',
    price: 320000,
    stock: 23,
    status: 'active',
    images: ['/images/products/space-sheet.jpg'],
    description: 'Ga giường cotton với họa tiết vũ trụ độc đáo',
    featured: false,
    createdAt: '2026-01-25T13:00:00Z',
    updatedAt: '2026-02-04T10:00:00Z',
    sales: 45,
  },
  {
    id: 'PRD005',
    name: 'Nệm cao su non Premium',
    sku: 'PR-MAT-005',
    type: 'single',
    category: 'Nệm',
    price: 1200000,
    stock: 12,
    status: 'active',
    images: ['/images/products/premium-mattress.jpg'],
    description: 'Nệm cao su non chống ẩm mốc, an toàn cho bé',
    featured: true,
    createdAt: '2026-01-05T08:00:00Z',
    updatedAt: '2026-02-03T12:00:00Z',
    sales: 34,
  },
];

export const mockCombos: Combo[] = [
  {
    id: 'CMB001',
    name: 'Combo Sweet Dreams',
    sku: 'SD-CMB-001',
    type: 'combo',
    category: 'Combo',
    price: 1500000,
    salePrice: 1200000,
    stock: 15,
    status: 'active',
    images: ['/images/combos/sweet-dreams.jpg'],
    description: 'Bộ combo hoàn hảo cho phòng ngủ bé yêu',
    featured: true,
    createdAt: '2026-01-12T10:00:00Z',
    updatedAt: '2026-02-05T15:00:00Z',
    sales: 67,
    items: [
      { productId: 'PRD001', productName: 'Bộ chăn ga gối Baby Dream', quantity: 1 },
      { productId: 'PRD002', productName: 'Gối ôm thú bông Unicorn', quantity: 1 },
      { productId: 'PRD003', productName: 'Chăn mền 4 mùa Comfort', quantity: 1 },
    ],
    discount: 20,
  },
  {
    id: 'CMB002',
    name: 'Combo Starter Kit',
    sku: 'SK-CMB-002',
    type: 'combo',
    category: 'Combo',
    price: 900000,
    salePrice: 750000,
    stock: 28,
    status: 'active',
    images: ['/images/combos/starter-kit.jpg'],
    description: 'Bộ combo cơ bản cho bé sơ sinh',
    featured: false,
    createdAt: '2026-01-18T11:00:00Z',
    updatedAt: '2026-02-02T09:00:00Z',
    sales: 92,
    items: [
      { productId: 'PRD001', productName: 'Bộ chăn ga gối Baby Dream', quantity: 1 },
      { productId: 'PRD004', productName: 'Ga giường họa tiết vũ trụ', quantity: 2 },
    ],
    discount: 16,
  },
];

export const categories = [
  'Bộ chăn ga',
  'Gối',
  'Chăn',
  'Ga giường',
  'Nệm',
  'Combo',
];
