export { default as ProfileSidebar } from "./ProfileSidebar"
export { default as ProfileInfoTab } from "./ProfileInfoTab"
export { default as BabiesTab } from "./BabiesTab"
export { default as OrdersTab } from "./OrdersTab"
export { default as WishlistTab } from "./WishlistTab"
export { default as AddressesTab } from "./AddressesTab"
export { default as NotificationsTab } from "./NotificationsTab"
export { default as SecurityTab } from "./SecurityTab"
