import type { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Cherubble 4-Layer Muslin Blanket",
    slug: "cherubble-4-layer-muslin-blanket",
    price: 35.0,
    originalPrice: 45.0,
    discount: 22,
    rating: 5,
    reviewCount: 128,
    image:
      "https://i.pinimg.com/736x/7c/aa/33/7caa33bf8eca070ee8a1dd20f86723ec.jpg",
    category: "Mattresses",
    material: "Cotton",
    ageRange: "0-12 months",
    inStock: true,
    isNew: true,
  },
  {
    id: "2",
    name: "Silk Fabric Baby Bedding Set",
    slug: "silk-fabric-baby-bedding-set",
    price: 28.0,
    originalPrice: 38.0,
    discount: 26,
    rating: 4.5,
    reviewCount: 89,
    image: "https://i.pinimg.com/736x/7c/aa/33/7caa33bf8eca070ee8a1dd20f86723ec.jpg",
    category: "Mattresses",
    material: "Silk",
    ageRange: "0-6 months",
    inStock: true,
    isNew: true,
  },
  {
    id: "3",
    name: "Baby fleece blanket, high quality",
    slug: "baby-fleece-blanket-high-quality",
    price: 28.0,
    originalPrice: 35.0,
    discount: 20,
    rating: 4,
    reviewCount: 45,
    image: "https://i.pinimg.com/736x/7c/aa/33/7caa33bf8eca070ee8a1dd20f86723ec.jpg",
    category: "Mattresses",
    material: "Fleece",
    ageRange: "6-12 months",
    inStock: true,
  },
  {
    id: "4",
    name: "Silk Fabric Baby Bedding Set",
    slug: "silk-fabric-baby-bedding-set-2",
    price: 29.0,
    originalPrice: 35.0,
    discount: 17,
    rating: 4.5,
    reviewCount: 67,
    image: "https://i.pinimg.com/736x/7c/aa/33/7caa33bf8eca070ee8a1dd20f86723ec.jpg",
    category: "Mattresses",
    material: "Cotton",
    ageRange: "0-12 months",
    inStock: true,
    isNew: true,
  },
  {
    id: "5",
    name: "Silk Fabric Baby Bedding Set Blue",
    slug: "silk-fabric-baby-bedding-set-blue",
    price: 28.0,
    originalPrice: 35.0,
    discount: 20,
    rating: 5,
    reviewCount: 92,
    image: "https://i.pinimg.com/736x/7c/aa/33/7caa33bf8eca070ee8a1dd20f86723ec.jpg",
    category: "Mattresses",
    material: "Silk",
    ageRange: "0-6 months",
    inStock: true,
    isBestSeller: true,
  },
  {
    id: "6",
    name: "This bedding set is made exclusively",
    slug: "bedding-set-exclusive",
    price: 29.0,
    originalPrice: 35.0,
    discount: 17,
    rating: 4.5,
    reviewCount: 54,
    image: "/images/products/bedding-4.jpg",
    category: "Mattresses",
    material: "Cotton",
    ageRange: "12-24 months",
    inStock: true,
    isNew: true,
  },
  {
    id: "7",
    name: "Cotton bedding set for baby",
    slug: "cotton-bedding-set-baby",
    price: 25.0,
    originalPrice: 30.0,
    discount: 17,
    rating: 4,
    reviewCount: 38,
    image: "/images/products/bedding-5.jpg",
    category: "Mattresses",
    material: "Cotton",
    ageRange: "0-12 months",
    inStock: true,
    isNew: true,
  },
  {
    id: "8",
    name: "Cotton bedding set for boys",
    slug: "cotton-bedding-set-boys",
    price: 36.0,
    originalPrice: 42.0,
    discount: 14,
    rating: 4.5,
    reviewCount: 71,
    image: "/images/products/bedding-6.jpg",
    category: "Mattresses",
    material: "Cotton",
    ageRange: "12-24 months",
    inStock: true,
  },
  {
    id: "9",
    name: "Cotton bedding set for boys premium",
    slug: "cotton-bedding-set-boys-premium",
    price: 28.0,
    originalPrice: 35.0,
    discount: 20,
    rating: 5,
    reviewCount: 115,
    image: "/images/products/bedding-7.jpg",
    category: "Mattresses",
    material: "Cotton",
    ageRange: "6-12 months",
    inStock: true,
    isBestSeller: true,
  },
];

export const categories = [
  "All",
  "Mattresses",
  "Pillows",
  "Bedding Sets",
  "Blankets",
];
export const materials = ["All", "Cotton", "Silk", "Fleece", "Organic Cotton"];
export const ageRanges = [
  "All",
  "0-6 months",
  "6-12 months",
  "12-24 months",
  "2+ years",
];
export const sortOptions = [
  { value: "default", label: "Default sorting" },
  { value: "price-asc", label: "Price: Low to High" },
  { value: "price-desc", label: "Price: High to Low" },
  { value: "newest", label: "Newest" },
  { value: "rating", label: "Highest Rating" },
];
